name: loki-stack
version: 0.1.0
description: Helm chart for deploying Loki stack with Filebeat, Fluent Bit, Grafana, Logstash, Loki, Prometheus, and Promtail.
maintainers:
  - name: Hadi Alizadeh
    email: alizadehadi08@gmail.com
dependencies:
  - name: loki
    version: 2.9.5
    repository: "https://grafana.github.io/helm-charts"
  - name: promtail
    version: 3.9.0
    repository: "https://grafana.github.io/helm-charts"
  - name: grafana
    version: 6.58.7
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus
    version: 25.4.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: logstash
    version: 1.2.0
    repository: "https://helm.elastic.co"
  - name: filebeat
    version: 7.17.3
    repository: "https://helm.elastic.co"
  - name: fluent-bit
    version: 0.36.0
    repository: "https://fluent.github.io/helm-charts"

defaults:
  filebeat:
    enabled: false
  fluent-bit:
    enabled: false
  grafana:
    enabled: false
  logstash:
    enabled: false
  loki:
    enabled: true
  prometheus:
    enabled: false
  promtail:
    enabled: true
  proxy:
    http_proxy: ''
    https_proxy: ''
    no_proxy: ''
